
import { KeyTerm } from './types';

export const KEY_TERMS: KeyTerm[] = [
    // --- A-LEVEL: WATER AND CARBON CYCLES ---
    { name: 'Carbon Budget', topic: 'Water and Carbon Cycles', details: 'The difference between the inputs of carbon into a subsystem and outputs of carbon from it.', citation: 'Concept: Systems', type: 'term', levels: ['A-Level'] },
    { name: 'Carbon Sequestration', topic: 'Water and Carbon Cycles', details: 'The removal and storage of carbon from the atmosphere in carbon sinks (oceans, forests, soils).', citation: 'Process: Mitigation', type: 'term', levels: ['A-Level'] },
    { name: 'Cryosphere', topic: 'Water and Carbon Cycles', details: 'Portions of Earth\'s surface where water is in solid form (ice sheets, glaciers, snow, permafrost).', citation: 'Store: Water Cycle', type: 'term', levels: ['A-Level'] },
    { name: 'Lithosphere', topic: 'Water and Carbon Cycles', details: 'Rigid outer part of Earth (crust and upper mantle). Largest store of carbon (>99%).', citation: 'Store: Carbon Cycle', type: 'term', levels: ['A-Level'] },
    { name: 'Stemflow', topic: 'Water and Carbon Cycles', details: 'Flow of intercepted water down the trunk or stem of a plant to the ground.', citation: 'Process: Water Cycle', type: 'term', levels: ['A-Level'] },
    { name: 'Throughfall', topic: 'Water and Carbon Cycles', details: 'Water reaching the ground directly or dripping off leaves.', citation: 'Process: Water Cycle', type: 'term', levels: ['A-Level'] },
    { name: 'Water Balance', topic: 'Water and Carbon Cycles', details: 'Relationship between precipitation, soil moisture, evapotranspiration, and runoff (P = Q + E +/- S).', citation: 'Concept: Hydrology', type: 'term', levels: ['A-Level'] },
    { name: 'Anthropogenic CO2', topic: 'Water and Carbon Cycles', details: 'Carbon dioxide generated by human activities (fossil fuels, deforestation).', citation: 'Concept: Climate Change', type: 'term', levels: ['A-Level'] },
    { name: 'Sere (Serial Stage)', topic: 'Water and Carbon Cycles', details: 'Intermediate stage in ecological succession advancing towards a climax community.', citation: 'Concept: Ecosystems', type: 'term', levels: ['A-Level'] },
    { name: 'Carbon Pump', topic: 'Water and Carbon Cycles', details: 'Mechanisms (biological and physical) that move carbon from the atmosphere to the deep ocean.', citation: 'Process: Carbon Cycle', type: 'term', levels: ['A-Level'] },
    { name: 'Peat', topic: 'Water and Carbon Cycles', details: 'Partially decayed plant matter found in bogs. A significant carbon store.', citation: 'Store: Carbon', type: 'term', levels: ['A-Level'] },
    { name: 'Enhanced Greenhouse Effect', topic: 'Water and Carbon Cycles', details: 'The strengthening of the natural greenhouse effect through human activities.', citation: 'Concept: Climate', type: 'term', levels: ['A-Level'] },

    // --- A-LEVEL: COASTAL SYSTEMS ---
    { name: 'Sediment Cell', topic: 'Coastal Systems and Landscapes', details: 'A length of coastline and its associated nearshore area within which the movement of coarse sediment is largely self-contained.', citation: 'Concept: Systems', type: 'term', levels: ['A-Level'] },
    { name: 'Isostatic Change', topic: 'Coastal Systems and Landscapes', details: 'Local rise or fall in land level relative to the sea (e.g., post-glacial rebound).', citation: 'Process: Sea Level', type: 'term', levels: ['A-Level'] },
    { name: 'Eustatic Change', topic: 'Coastal Systems and Landscapes', details: 'Global rise or fall in sea level caused by change in the volume of water or basin shape.', citation: 'Process: Sea Level', type: 'term', levels: ['A-Level'] },
    { name: 'Dynamic Equilibrium', topic: 'Coastal Systems and Landscapes', details: 'A state of balance between inputs and outputs in a system, where the system adjusts to change.', citation: 'Concept: Systems', type: 'term', levels: ['A-Level'] },
    { name: 'Fjord', topic: 'Coastal Systems and Landscapes', details: 'A drowned glacial valley with steep sides and a U-shaped cross-section.', citation: 'Landform: Submergent', type: 'term', levels: ['A-Level'] },
    { name: 'Ria', topic: 'Coastal Systems and Landscapes', details: 'A drowned river valley in an unglaciated area.', citation: 'Landform: Submergent', type: 'term', levels: ['A-Level'] },
    { name: 'Sub-aerial Weathering', topic: 'Coastal Systems and Landscapes', details: 'Processes (mechanical, chemical, biological) that break down rock in situ on the cliff face.', citation: 'Process: Weathering', type: 'term', levels: ['A-Level'] },
    { name: 'Tombolo', topic: 'Coastal Systems and Landscapes', details: 'A spit connecting an island to the mainland.', citation: 'Landform: Deposition', type: 'term', levels: ['A-Level'] },
    { name: 'Dalmatian Coast', topic: 'Coastal Systems and Landscapes', details: 'A submergent landscape where valleys and ridges run parallel to the coast.', citation: 'Landform: Submergent', type: 'term', levels: ['A-Level'] },
    { name: 'Managed Retreat', topic: 'Coastal Systems and Landscapes', details: 'Allowing the shoreline to move naturally (often inland) rather than attempting to hold the line.', citation: 'Strategy: Management', type: 'term', levels: ['A-Level'] },

    // --- A-LEVEL: HAZARDS ---
    { name: 'Liquefaction', topic: 'Hazards', details: 'Process where saturated soil loses strength and stiffness in response to earthquake shaking, behaving like a liquid.', citation: 'Process: Seismic', type: 'term', levels: ['A-Level'] },
    { name: 'Jokulhlaup', topic: 'Hazards', details: 'A type of glacial outburst flood, often triggered by volcanic eruption under ice.', citation: 'Hazard: Volcanic', type: 'term', levels: ['A-Level'] },
    { name: 'Pyroclastic Flow', topic: 'Hazards', details: 'A fast-moving current of hot gas and volcanic matter (tephra).', citation: 'Hazard: Volcanic', type: 'term', levels: ['A-Level'] },
    { name: 'Benioff Zone', topic: 'Hazards', details: 'A planar zone of seismicity corresponding with the down-going slab in a subduction zone.', citation: 'Structure: Tectonics', type: 'term', levels: ['A-Level'] },
    { name: 'Asthenosphere', topic: 'Hazards', details: 'The upper layer of the earth\'s mantle, below the lithosphere, where convection occurs.', citation: 'Structure: Earth', type: 'term', levels: ['A-Level'] },
    { name: 'Hydrometeorological Hazard', topic: 'Hazards', details: 'Hazards caused by atmospheric or hydrological processes (e.g., floods, cyclones, drought).', citation: 'Classification', type: 'term', levels: ['A-Level'] },
    { name: 'Multi-Hazard Zone', topic: 'Hazards', details: 'An area where two or more hazards occur, and where they may interact (e.g., The Philippines).', citation: 'Concept: Risk', type: 'term', levels: ['A-Level'] },
    { name: 'Retrofitting', topic: 'Hazards', details: 'Adding new technology or features to older systems (e.g., earthquake-proofing buildings).', citation: 'Strategy: Mitigation', type: 'term', levels: ['A-Level'] },
    { name: 'Slab Pull', topic: 'Hazards', details: 'The force exerted by a cold, dense oceanic plate plunging into the mantle due to its own weight.', citation: 'Process: Tectonics', type: 'term', levels: ['A-Level'] },

    // --- A-LEVEL: GLOBAL SYSTEMS & GOVERNANCE ---
    { name: 'Global Shift', topic: 'Global Systems and Global Governance', details: 'The movement of manufacturing and economic activity from HICs to NEEs and LICs.', citation: 'Concept: Globalisation', type: 'term', levels: ['A-Level'] },
    { name: 'Remittances', topic: 'Global Systems and Global Governance', details: 'Transfers of money made by foreign workers to family in their home country.', citation: 'Concept: Flows', type: 'term', levels: ['A-Level'] },
    { name: 'Foreign Direct Investment (FDI)', topic: 'Global Systems and Global Governance', details: 'Investment made by a firm or individual in one country into business interests in another country.', citation: 'Concept: Flows', type: 'term', levels: ['A-Level'] },
    { name: 'Gini Coefficient', topic: 'Global Systems and Global Governance', details: 'A statistical measure of economic inequality (0 = perfect equality, 1 = max inequality).', citation: 'Measure: Inequality', type: 'term', levels: ['A-Level'] },
    { name: 'Deregulation', topic: 'Global Systems and Global Governance', details: 'The reduction or elimination of government power in a particular industry to create more competition.', citation: 'Process: Economics', type: 'term', levels: ['A-Level'] },
    { name: 'Global Commons', topic: 'Global Systems and Global Governance', details: 'Resource domains that lie outside of the political reach of any one nation state (High Seas, Atmosphere, Antarctica, Space).', citation: 'Concept: Governance', type: 'term', levels: ['A-Level'] },
    { name: 'Vertical Integration', topic: 'Global Systems and Global Governance', details: 'When a company controls multiple stages of production (e.g., supply chain and distribution).', citation: 'Concept: TNCs', type: 'term', levels: ['A-Level'] },
    { name: 'Horizontal Integration', topic: 'Global Systems and Global Governance', details: 'When a company increases production of goods or services at the same part of the supply chain (e.g., buying a competitor).', citation: 'Concept: TNCs', type: 'term', levels: ['A-Level'] },
    { name: 'Diaspora', topic: 'Global Systems and Global Governance', details: 'A scattered population whose origin lies in a separate geographic locale.', citation: 'Concept: Migration', type: 'term', levels: ['A-Level'] },

    // --- A-LEVEL: CHANGING PLACES ---
    { name: 'Endogenous Factors', topic: 'Changing Places', details: 'Internal factors that help shape the character of a place (e.g., location, topography, land use, infrastructure).', citation: 'Concept: Place', type: 'term', levels: ['A-Level'] },
    { name: 'Exogenous Factors', topic: 'Changing Places', details: 'External factors that shape the character of a place (e.g., flows of people, capital, resources, and ideas).', citation: 'Concept: Place', type: 'term', levels: ['A-Level'] },
    { name: 'Placelessness', topic: 'Changing Places', details: 'The loss of uniqueness of place in the cultural landscape so that one place looks like the next (e.g., Clone Towns).', citation: 'Concept: Identity', type: 'term', levels: ['A-Level'] },
    { name: 'Gentrification', topic: 'Changing Places', details: 'Process of renovating deteriorated urban neighborhoods by means of the influx of more affluent residents.', citation: 'Process: Urban', type: 'term', levels: ['A-Level'] },
    { name: 'Rebranding', topic: 'Changing Places', details: 'Developing a place to change its image and the way it is perceived (Re-imaging + Regeneration).', citation: 'Strategy: Place', type: 'term', levels: ['A-Level'] },
    { name: 'Topophilia', topic: 'Changing Places', details: 'A strong sense of place, which often mixes with the sense of cultural identity.', citation: 'Concept: Perception', type: 'term', levels: ['A-Level'] },
    { name: 'Insider/Outsider', topic: 'Changing Places', details: 'The perspective of someone who knows a place well vs. someone who does not (or feels excluded).', citation: 'Concept: Perception', type: 'term', levels: ['A-Level'] },
    { name: 'Glocalisation', topic: 'Changing Places', details: 'The adaptation of global products/services to local markets (e.g., McDonald\'s menus).', citation: 'Concept: Place', type: 'term', levels: ['A-Level'] },

    // --- A-LEVEL: CONTEMPORARY URBAN ENVIRONMENTS ---
    { name: 'Urban Heat Island', topic: 'Contemporary Urban Environments', details: 'An urban area or metropolitan area that is significantly warmer than its surrounding rural areas.', citation: 'Phenomenon: Climate', type: 'term', levels: ['A-Level'] },
    { name: 'Edge City', topic: 'Contemporary Urban Environments', details: 'A concentration of business, shopping, and entertainment outside a traditional downtown in what had been residential or rural.', citation: 'Form: Urban', type: 'term', levels: ['A-Level'] },
    { name: 'Fortress Landscape', topic: 'Contemporary Urban Environments', details: 'Landscapes designed around security, protection, surveillance, and exclusion.', citation: 'Concept: Design', type: 'term', levels: ['A-Level'] },
    { name: 'World City', topic: 'Contemporary Urban Environments', details: 'A city considered to be an important node in the global economic system.', citation: 'Concept: Globalisation', type: 'term', levels: ['A-Level'] },
    { name: 'Sustainable Drainage Systems (SuDS)', topic: 'Contemporary Urban Environments', details: 'Water management practices to reduce surface water runoff and prevent flooding in urban areas.', citation: 'Strategy: Management', type: 'term', levels: ['A-Level'] },
    { name: 'Urban Resurgence', topic: 'Contemporary Urban Environments', details: 'Regeneration, both economic and structural, of an urban area which has suffered a period of decline.', citation: 'Process: Urban', type: 'term', levels: ['A-Level'] },

    // --- A-LEVEL: POPULATION & ENVIRONMENT ---
    { name: 'Epidemiological Transition', topic: 'Population and the Environment', details: 'The changing pattern of disease seen as countries experience social and economic development.', citation: 'Model: Health', type: 'term', levels: ['A-Level'] },
    { name: 'Carrying Capacity', topic: 'Population and the Environment', details: 'The maximum population size of a biological species that can be sustained in a specific environment.', citation: 'Concept: Ecology', type: 'term', levels: ['A-Level'] },
    { name: 'Demographic Dividend', topic: 'Population and the Environment', details: 'Economic growth potential that can result from shifts in a population’s age structure (more workers, fewer dependents).', citation: 'Concept: Economics', type: 'term', levels: ['A-Level'] },
    { name: 'Food Security', topic: 'Population and the Environment', details: 'When all people at all times have access to sufficient, safe, nutritious food.', citation: 'Concept: Resources', type: 'term', levels: ['A-Level'] },
    { name: 'Replacement Level', topic: 'Population and the Environment', details: 'The fertility rate needed to maintain a population size (approx 2.1).', citation: 'Concept: Demography', type: 'term', levels: ['A-Level'] },

    // --- GCSE: NATURAL HAZARDS ---
    { name: 'Natural Hazard', topic: 'The Challenge of Natural Hazards', details: 'A natural event (e.g., earthquake, flood) that threatens people or property.', citation: 'Definition', type: 'term', levels: ['GCSE'] },
    { name: 'Convection Currents', topic: 'The Challenge of Natural Hazards', details: 'Circular currents in the mantle caused by magma being heated by the core.', citation: 'Process: Tectonics', type: 'term', levels: ['GCSE'] },
    { name: 'Subduction Zone', topic: 'The Challenge of Natural Hazards', details: 'Where oceanic plate is forced down into the mantle beneath a continental plate.', citation: 'Process: Tectonics', type: 'term', levels: ['GCSE'] },
    { name: 'Primary Effects', topic: 'The Challenge of Natural Hazards', details: 'The initial impact of a natural event on people and property, caused directly by it.', citation: 'Concept: Impacts', type: 'term', levels: ['GCSE'] },
    { name: 'Secondary Effects', topic: 'The Challenge of Natural Hazards', details: 'The after-effects that occur as indirect impacts of a natural event.', citation: 'Concept: Impacts', type: 'term', levels: ['GCSE'] },
    { name: 'Immediate Responses', topic: 'The Challenge of Natural Hazards', details: 'Reaction of people as the disaster happens (e.g., search and rescue).', citation: 'Concept: Management', type: 'term', levels: ['GCSE'] },
    { name: 'Long-term Responses', topic: 'The Challenge of Natural Hazards', details: 'Later reactions that occur in the weeks/months/years after (e.g., rebuilding).', citation: 'Concept: Management', type: 'term', levels: ['GCSE'] },
    { name: 'Coriolis Effect', topic: 'The Challenge of Natural Hazards', details: 'The effect of Earth\'s rotation on the direction of winds and currents.', citation: 'Concept: Weather', type: 'term', levels: ['GCSE'] },

    // --- GCSE: LIVING WORLD ---
    { name: 'Ecosystem', topic: 'The Living World', details: 'A community of plants and animals that interact with each other and their physical environment.', citation: 'Concept: Ecology', type: 'term', levels: ['GCSE'] },
    { name: 'Producer', topic: 'The Living World', details: 'An organism or plant that is able to absorb energy from the sun through photosynthesis.', citation: 'Role: Ecosystem', type: 'term', levels: ['GCSE'] },
    { name: 'Consumer', topic: 'The Living World', details: 'Creature that eats herbivores and/or plant matter.', citation: 'Role: Ecosystem', type: 'term', levels: ['GCSE'] },
    { name: 'Decomposer', topic: 'The Living World', details: 'An organism causing decay (e.g., bacteria/fungi) breaking down dead tissue.', citation: 'Role: Ecosystem', type: 'term', levels: ['GCSE'] },
    { name: 'Food Web', topic: 'The Living World', details: 'A complex hierarchy of plants and animals relying on each other for food.', citation: 'Concept: Ecology', type: 'term', levels: ['GCSE'] },
    { name: 'Biodiversity', topic: 'The Living World', details: 'The variety of life in the world or in a particular habitat.', citation: 'Concept: Ecology', type: 'term', levels: ['GCSE'] },
    { name: 'Buttress Roots', topic: 'The Living World', details: 'Large roots above the ground to support tall trees in shallow rainforest soil.', citation: 'Adaptation', type: 'term', levels: ['GCSE'] },
    { name: 'Drip Tip', topic: 'The Living World', details: 'Pointy ends on leaves to allow water to run off quickly, preventing mould.', citation: 'Adaptation', type: 'term', levels: ['GCSE'] },

    // --- GCSE: PHYSICAL LANDSCAPES ---
    { name: 'Hydraulic Action', topic: 'Physical Landscapes in the UK', details: 'The force of water colliding with rocks breaks rock particles away.', citation: 'Process: Erosion', type: 'term', levels: ['GCSE'] },
    { name: 'Abrasion', topic: 'Physical Landscapes in the UK', details: 'Rocks carried by water are rubbed against the bed and banks/cliffs.', citation: 'Process: Erosion', type: 'term', levels: ['GCSE'] },
    { name: 'Attrition', topic: 'Physical Landscapes in the UK', details: 'Stones collide with each other, becoming smaller and rounder.', citation: 'Process: Erosion', type: 'term', levels: ['GCSE'] },
    { name: 'Solution', topic: 'Physical Landscapes in the UK', details: 'Dissolving of soluble chemicals in rocks (e.g., limestone).', citation: 'Process: Erosion', type: 'term', levels: ['GCSE'] },
    { name: 'Longshore Drift', topic: 'Physical Landscapes in the UK', details: 'Movement of sediment along the coast by waves approaching at an angle.', citation: 'Process: Coastal', type: 'term', levels: ['GCSE'] },
    { name: 'Spit', topic: 'Physical Landscapes in the UK', details: 'Extended stretch of beach material projecting out to sea.', citation: 'Landform: Deposition', type: 'term', levels: ['GCSE'] },
    { name: 'V-shaped Valley', topic: 'Physical Landscapes in the UK', details: 'Steep-sided valley formed by vertical erosion in the upper course of a river.', citation: 'Landform: River', type: 'term', levels: ['GCSE'] },
    
    // --- GCSE: URBAN ISSUES ---
    { name: 'Urbanisation', topic: 'Urban Issues and Challenges', details: 'Increasing percentage of a country\'s population living in towns and cities.', citation: 'Concept: Population', type: 'term', levels: ['GCSE'] },
    { name: 'Megacity', topic: 'Urban Issues and Challenges', details: 'An urban area with a total population in excess of ten million people.', citation: 'Concept: Urban', type: 'term', levels: ['GCSE'] },
    { name: 'Rural-urban migration', topic: 'Urban Issues and Challenges', details: 'Movement of people from the countryside to the city.', citation: 'Concept: Migration', type: 'term', levels: ['GCSE'] },
    { name: 'Squatter Settlement', topic: 'Urban Issues and Challenges', details: 'Area of poor quality housing, lacking amenities, often illegal.', citation: 'Concept: Urban', type: 'term', levels: ['GCSE'] },
    { name: 'Brownfield Site', topic: 'Urban Issues and Challenges', details: 'Land that has been used, abandoned and now awaits some new use.', citation: 'Concept: Planning', type: 'term', levels: ['GCSE'] },
    
    // --- GCSE: ECONOMIC WORLD ---
    { name: 'GNI', topic: 'The Changing Economic World', details: 'Gross National Income: Total value of goods/services plus money earned from abroad.', citation: 'Measure: Development', type: 'term', levels: ['GCSE'] },
    { name: 'HDI', topic: 'The Changing Economic World', details: 'Human Development Index: Composite measure using life expectancy, education, and income.', citation: 'Measure: Development', type: 'term', levels: ['GCSE'] },
    { name: 'NEE', topic: 'The Changing Economic World', details: 'Newly Emerging Economy: Country experiencing high rates of economic development.', citation: 'Concept: Development', type: 'term', levels: ['GCSE'] },
    { name: 'Demographic Transition Model', topic: 'The Changing Economic World', details: 'Model showing how population changes over time as a country develops.', citation: 'Model: Population', type: 'term', levels: ['GCSE'] },
    { name: 'TNC', topic: 'The Changing Economic World', details: 'Transnational Corporation: Company operating in more than one country.', citation: 'Concept: Globalisation', type: 'term', levels: ['GCSE'] },

    // --- GCSE: RESOURCE MANAGEMENT ---
    { name: 'Resource Management', topic: 'The Challenge of Resource Management', details: 'Control and monitoring of resources so they do not become depleted.', citation: 'Concept: Sustainability', type: 'term', levels: ['GCSE'] },
    { name: 'Carbon Footprint', topic: 'The Challenge of Resource Management', details: 'Measurement of greenhouse gases we individually produce.', citation: 'Concept: Environment', type: 'term', levels: ['GCSE'] },
    { name: 'Food Miles', topic: 'The Challenge of Resource Management', details: 'Distance covered by food from growing to plate.', citation: 'Concept: Sustainability', type: 'term', levels: ['GCSE'] },
    { name: 'Fracking', topic: 'The Challenge of Resource Management', details: 'Hydraulic fracturing to release gas inside rock.', citation: 'Process: Energy', type: 'term', levels: ['GCSE'] }
];
